version: '3.8'
services:
  json-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/app/db.json
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - json-server
    restart: always